export const SERVICES = [
  {
    slug: 'air-conditioning',
    name: 'Air Conditioning',
    icon: '❄️',
    tagline: 'Stay cool all summer long',
    shortDesc: 'Expert AC installation, repair & maintenance for homes and businesses.',
    heroImage: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=1200&q=80',
    color: 'from-blue-500 to-cyan-400',
    features: ['AC Installation & Replacement','Emergency AC Repair','Seasonal Tune-Ups','Refrigerant Recharge','Smart Thermostat Setup','Energy Efficiency Upgrades'],
    benefits: [
      { icon:'⚡', title:'Same-Day Service', desc:'Most AC repairs completed the same day you call.' },
      { icon:'🏅', title:'All Brands', desc:'Carrier, Trane, Lennox, Rheem, Goodman & more.' },
      { icon:'💰', title:'Upfront Pricing', desc:'No surprises. We quote before we work.' },
    ],
    description: 'From emergency AC repairs to complete system replacements, our NATE-certified technicians deliver fast, reliable air conditioning service. We service all major brands and back every job with our satisfaction guarantee.',
    metaTitle: 'AC Repair & Installation | TruFlow Heating & Cooling',
    metaDesc: 'Professional air conditioning repair, installation & maintenance. 24/7 emergency service across Chicagoland.',
  },
  {
    slug: 'heating',
    name: 'Heating',
    icon: '🔥',
    tagline: 'Stay warm through every Chicago winter',
    shortDesc: 'Furnace repair, heat pump installation & complete heating solutions.',
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
    color: 'from-orange-500 to-red-400',
    features: ['Furnace Repair & Replacement','Heat Pump Installation','Boiler Service & Repair','Ductless Mini-Split Systems','Emergency Heating Service','Carbon Monoxide Testing'],
    benefits: [
      { icon:'🌙', title:'24/7 Emergency', desc:'No heat in winter? We respond within 1-2 hours.' },
      { icon:'🔧', title:'All Systems', desc:'Gas, electric, heat pump, boiler — we service everything.' },
      { icon:'🛡️', title:'Safety First', desc:'CO testing included with every furnace service.' },
    ],
    description: 'Don\'t let a failing furnace leave your family in the cold. Our heating specialists are on call 24/7 for emergency furnace repairs, heat pump installations, and complete heating system upgrades.',
    metaTitle: 'Furnace Repair & Heating Service | TruFlow HVAC',
    metaDesc: 'Emergency furnace repair, heating installation & maintenance. 24/7 service in Chicagoland suburbs.',
  },
  {
    slug: 'installation',
    name: 'Installation',
    icon: '🔧',
    tagline: 'New systems installed right the first time',
    shortDesc: 'Complete HVAC system installation for homes and commercial properties.',
    heroImage: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=1200&q=80',
    color: 'from-violet-500 to-purple-400',
    features: ['Complete System Installation','Residential & Commercial','Free In-Home Estimates','Energy Star Equipment','Permit Procurement','Financing Available'],
    benefits: [
      { icon:'📋', title:'Free Estimates', desc:'No obligation in-home quotes for new systems.' },
      { icon:'💳', title:'Flexible Financing', desc:'0% interest options available for qualified buyers.' },
      { icon:'🎁', title:'Utility Rebates', desc:'We help you maximize manufacturer and utility rebates.' },
    ],
    description: 'Investing in a new HVAC system is one of the most important decisions for your home. Our installation experts help you select the right equipment and ensure flawless setup backed by manufacturer warranties.',
    metaTitle: 'HVAC Installation Services | TruFlow Heating & Cooling',
    metaDesc: 'Professional HVAC system installation for homes and businesses. Free estimates. Chicagoland suburbs.',
  },
  {
    slug: 'maintenance',
    name: 'Maintenance',
    icon: '🛡️',
    tagline: 'Prevent breakdowns before they happen',
    shortDesc: 'Routine HVAC tune-ups & preventive maintenance plans.',
    heroImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200&q=80',
    color: 'from-green-500 to-emerald-400',
    features: ['Annual System Tune-Ups','Filter Replacement Service','Coil & Duct Cleaning','Safety Inspections','Refrigerant Level Check','Priority Service Plans'],
    benefits: [
      { icon:'📉', title:'Lower Bills', desc:'Clean systems run up to 15% more efficiently.' },
      { icon:'⏳', title:'Longer Life', desc:'Add 5–10 years to your HVAC equipment lifespan.' },
      { icon:'🚨', title:'Fewer Breakdowns', desc:'Catch issues before they become expensive emergencies.' },
    ],
    description: 'Regular maintenance is the single most effective way to extend HVAC life, reduce energy bills, and prevent costly emergency breakdowns. Our comprehensive tune-up includes 21-point inspection and cleaning.',
    metaTitle: 'HVAC Maintenance Plans | TruFlow Heating & Cooling',
    metaDesc: 'Preventive HVAC maintenance and annual tune-up plans. Keep your system running at peak performance.',
  },
  {
    slug: 'air-quality',
    name: 'Air Quality',
    icon: '💨',
    tagline: 'Breathe cleaner, healthier air',
    shortDesc: 'Indoor air purification, filtration & ventilation solutions.',
    heroImage: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&q=80',
    color: 'from-teal-500 to-cyan-400',
    features: ['Whole-Home Air Purifiers','UV Light Sanitizers','Humidifiers & Dehumidifiers','Duct Cleaning & Sanitizing','HEPA Filtration Systems','Ventilation Solutions'],
    benefits: [
      { icon:'🫁', title:'Health Benefits', desc:'Remove allergens, mold spores, bacteria & viruses.' },
      { icon:'💧', title:'Balanced Humidity', desc:'Optimal moisture levels for comfort and health.' },
      { icon:'🌿', title:'Odor Elimination', desc:'Eliminate pet, smoke, cooking & musty odors.' },
    ],
    description: 'Indoor air can be 5x more polluted than outdoor air. Our air quality solutions — from UV purifiers to whole-home filtration — create a healthier environment for your family and reduce allergy symptoms.',
    metaTitle: 'Indoor Air Quality Services | TruFlow HVAC',
    metaDesc: 'Air purifiers, duct cleaning & ventilation solutions. Improve indoor air quality in your Chicagoland home.',
  },
];

export const getServiceBySlug = (slug) => SERVICES.find(s => s.slug === slug);
