export const SERVICES = [
  {
    slug: 'furnace-repair-installation',
    name: 'Furnace Repair & Installation',
    icon: '🔥',
    tagline: 'Stay warm through every Chicago winter',
    shortDesc: 'Expert furnace repair, replacement & installation for homes and businesses across Chicagoland.',
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
    color: 'from-orange-500 to-red-500',
    features: [
      'Emergency Furnace Repair',
      'New Furnace Installation',
      'Furnace Replacement',
      'All Brands Serviced',
      'Carbon Monoxide Testing',
      '10-Year Labor & Parts Warranty',
    ],
    benefits: [
      { icon: '⚡', title: 'Same-Day Service',    desc: 'Emergency furnace repairs completed same day — no waiting in the cold.' },
      { icon: '🏅', title: '10-Year Warranty',    desc: 'Labor & parts warranty on all Goodman installations.' },
      { icon: '🔒', title: 'Licensed & Insured',  desc: 'All technicians are EPA certified and fully background checked.' },
    ],
    description: 'Don\'t let a failing furnace leave your family in the cold. Our EPA-certified heating specialists are on call 24/7 for emergency furnace repairs, new installations, and complete system replacements. Every installation is backed by our 10-year labor & parts warranty.',
    metaTitle: 'Furnace Repair & Installation Chicago IL | TruFlow HVAC',
    metaDesc: 'Expert furnace repair & installation in Chicago Illinois. 10-year warranty. Licensed & insured. 24/7 emergency service.',
  },
  {
    slug: 'ac-repair-installation',
    name: 'AC Repair & Installation',
    icon: '❄️',
    tagline: 'Stay cool all summer long',
    shortDesc: 'Professional air conditioner repair, replacement & installation — fast response, honest pricing.',
    heroImage: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=1200&q=80',
    color: 'from-blue-500 to-cyan-400',
    features: [
      'Emergency AC Repair',
      'New AC Installation',
      'AC System Replacement',
      'Refrigerant Recharge',
      'Smart Thermostat Setup',
      'Energy Efficiency Upgrades',
    ],
    benefits: [
      { icon: '⚡', title: 'Fast Response',       desc: 'Same-day AC repair available — most jobs completed in one visit.' },
      { icon: '🏅', title: '10-Year Warranty',     desc: 'Factory-backed 10-year labor & parts warranty on installations.' },
      { icon: '💰', title: 'Upfront Pricing',     desc: 'We quote before we work. No hidden fees, no surprises.' },
    ],
    description: 'From emergency AC repairs to complete system replacements, our NATE-certified technicians deliver fast, reliable air conditioning service across Chicago Illinois. Every installation is backed by our 10-year labor & parts warranty.',
    metaTitle: 'AC Repair & Installation Chicago IL | TruFlow HVAC',
    metaDesc: 'Professional AC repair & installation in Chicago Illinois. 24/7 emergency service. Licensed & insured. Honest pricing.',
  },
  {
    slug: 'water-heaters',
    name: 'Water Heaters',
    icon: '🚿',
    tagline: 'Hot water when you need it most',
    shortDesc: 'Gas water heater installation, repair & maintenance — fast same-day service available.',
    heroImage: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=1200&q=80',
    color: 'from-yellow-500 to-orange-400',
    features: [
      'Gas Water Heater Installation',
      'Water Heater Repair',
      'Tank & Tankless Systems',
      'Emergency Replacement',
      'Code Compliant Installation',
      'All Major Brands Serviced',
    ],
    benefits: [
      { icon: '⚡', title: 'Same-Day Install',    desc: 'Hot water restored fast — same-day installation available.' },
      { icon: '🔒', title: 'Licensed & Insured',  desc: 'Fully licensed plumbing & HVAC technicians on every job.' },
      { icon: '💰', title: 'Honest Pricing',      desc: 'Upfront quotes with no hidden fees before we start.' },
    ],
    description: 'No hot water is an emergency. Our licensed technicians handle gas water heater installation, repair, and replacement for all major brands. We offer same-day service and ensure every installation is code-compliant and safely inspected before we leave.',
    metaTitle: 'Water Heaters Chicago IL | TruFlow',
    metaDesc: 'Water heater installation & repair in Chicago Illinois. Same-day service. Licensed & insured technicians.',
  },
  {
    slug: 'maintenance-tune-ups',
    name: 'Maintenance & Tune-Ups',
    icon: '🛡️',
    tagline: 'Prevent breakdowns before they happen',
    shortDesc: 'Routine HVAC tune-ups & preventive maintenance to keep your system running at peak performance.',
    heroImage: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200&q=80',
    color: 'from-green-500 to-emerald-400',
    features: [
      'Annual System Tune-Ups',
      'Filter Replacement',
      'Coil & Duct Cleaning',
      'Safety & Efficiency Inspection',
      'Refrigerant Level Check',
      'Priority Maintenance Plans',
    ],
    benefits: [
      { icon: '📉', title: 'Lower Energy Bills',  desc: 'Clean, tuned systems run up to 15% more efficiently.' },
      { icon: '⏳', title: 'Longer Equipment Life',desc: 'Add 5–10 years to your HVAC system lifespan.' },
      { icon: '🚨', title: 'Fewer Breakdowns',    desc: 'Catch small issues before they become costly emergencies.' },
    ],
    description: 'Regular maintenance is the most cost-effective way to extend HVAC life, reduce energy bills, and prevent costly emergency breakdowns. Our comprehensive tune-up includes a 21-point inspection, cleaning, and safety check — keeping your system running efficiently year-round.',
    metaTitle: 'HVAC Maintenance & Tune-Ups Chicago IL | TruFlow',
    metaDesc: 'Professional HVAC maintenance & tune-ups in Chicago Illinois. Prevent breakdowns, lower bills, extend system life.',
  },
  {
    slug: 'boiler-installation-repair',
    name: 'Water Heaters & Boiler',
    icon: '⚙️',
    tagline: 'Complete boiler & water heater solutions',
    shortDesc: 'Expert boiler installation, maintenance & repair — residential and commercial Chicagoland.',
    heroImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&q=80',
    color: 'from-slate-600 to-slate-800',
    features: [
      'Boiler Installation & Replacement',
      'Boiler Repair & Maintenance',
      'Gas Water Heater Installation',
      'Residential & Commercial',
      'Emergency Boiler Service',
      'All Major Brands Serviced',
    ],
    benefits: [
      { icon: '🌙', title: '24/7 Emergency',      desc: 'No heat or hot water? We respond within 1-2 hours.' },
      { icon: '🏅', title: 'EPA Certified Techs', desc: 'Every technician is certified, background-checked & insured.' },
      { icon: '✅', title: 'Satisfaction Guaranteed', desc: 'Not happy? We\'ll come back and make it right at no charge.' },
    ],
    description: 'From gas water heater installations to complete boiler systems, TruFlow handles all your hot water and heating needs. Our EPA-certified technicians service all major brands and provide 24/7 emergency response for residential and commercial customers across Chicagoland.',
    metaTitle: 'Boiler Installation & Repair Chicago IL | TruFlow HVAC',
    metaDesc: 'Boiler installation, repair & maintenance in Chicago Illinois. Gas water heater services. 24/7 emergency. Licensed & insured.',
  },
];

export const getServiceBySlug = (slug) => SERVICES.find(s => s.slug === slug);